create table energy_contribution (mw_contributed float(53) not null, energy_producer_id bigint, id bigint generated by default as identity, time_block_id bigint, primary key (id));
create table energy_producer (id bigint generated by default as identity, name varchar(255), type varchar(255) check (type in ('SOLAIRE','EOLIEN','HYDRAULIQUE')), primary key (id));
create table market (id integer generated by default as identity, type varchar(255) not null unique check (type in ('RESERVE_PRIMAIRE','RESERVE_SECONDAIRE','RESERVE_RAPIDE')), primary key (id));
create table offer (market_id integer, id bigint generated by default as identity, primary key (id));
create table time_block (floor_price float(53) not null, quantitymw float(53) not null, id bigint generated by default as identity, offer_id bigint, primary key (id));
alter table if exists energy_contribution add constraint FKiucrahaik72gsbyk7do84owuo foreign key (energy_producer_id) references energy_producer;
alter table if exists energy_contribution add constraint FK2c998xy5w9rcawoe6qxxw2f7u foreign key (time_block_id) references time_block;
alter table if exists offer add constraint FK1cr3qdcwnl0lmm66qmhgiaks1 foreign key (market_id) references market;
alter table if exists time_block add constraint FKrx7uvr5ui2sw4nx4x467cdyql foreign key (offer_id) references offer;
